<?php

use App\Models\Countries;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('country_id' => '1','country_sortname' => 'AF','country_name' => 'Afghanistan','country_code' => '93','country_status' => '0'),
            array('country_id' => '2','country_sortname' => 'AL','country_name' => 'Albania','country_code' => '355','country_status' => '0'),
            array('country_id' => '3','country_sortname' => 'DZ','country_name' => 'Algeria','country_code' => '213','country_status' => '0'),
            array('country_id' => '4','country_sortname' => 'AS','country_name' => 'American Samoa','country_code' => '1684','country_status' => '0'),
            array('country_id' => '5','country_sortname' => 'AD','country_name' => 'Andorra','country_code' => '376','country_status' => '0'),
            array('country_id' => '6','country_sortname' => 'AO','country_name' => 'Angola','country_code' => '244','country_status' => '0'),
            array('country_id' => '7','country_sortname' => 'AI','country_name' => 'Anguilla','country_code' => '1264','country_status' => '0'),
            array('country_id' => '8','country_sortname' => 'AQ','country_name' => 'Antarctica','country_code' => '672','country_status' => '0'),
            array('country_id' => '9','country_sortname' => 'AG','country_name' => 'Antigua And Barbuda','country_code' => '1268','country_status' => '0'),
            array('country_id' => '10','country_sortname' => 'AR','country_name' => 'Argentina','country_code' => '54','country_status' => '0'),
            array('country_id' => '11','country_sortname' => 'AM','country_name' => 'Armenia','country_code' => '374','country_status' => '1'),
            array('country_id' => '12','country_sortname' => 'AW','country_name' => 'Aruba','country_code' => '297','country_status' => '0'),
            array('country_id' => '13','country_sortname' => 'AU','country_name' => 'Australia','country_code' => '61','country_status' => '0'),
            array('country_id' => '14','country_sortname' => 'AT','country_name' => 'Austria','country_code' => '43','country_status' => '0'),
            array('country_id' => '15','country_sortname' => 'AZ','country_name' => 'Azerbaijan','country_code' => '994','country_status' => '1'),
            array('country_id' => '16','country_sortname' => 'BS','country_name' => 'Bahamas The','country_code' => '1242','country_status' => '0'),
            array('country_id' => '17','country_sortname' => 'BH','country_name' => 'Bahrain','country_code' => '973','country_status' => '0'),
            array('country_id' => '18','country_sortname' => 'BD','country_name' => 'Bangladesh','country_code' => '880','country_status' => '0'),
            array('country_id' => '19','country_sortname' => 'BB','country_name' => 'Barbados','country_code' => '1246','country_status' => '0'),
            array('country_id' => '20','country_sortname' => 'BY','country_name' => 'Belarus','country_code' => '375','country_status' => '0'),
            array('country_id' => '21','country_sortname' => 'BE','country_name' => 'Belgium','country_code' => '32','country_status' => '0'),
            array('country_id' => '22','country_sortname' => 'BZ','country_name' => 'Belize','country_code' => '501','country_status' => '0'),
            array('country_id' => '23','country_sortname' => 'BJ','country_name' => 'Benin','country_code' => '229','country_status' => '0'),
            array('country_id' => '24','country_sortname' => 'BM','country_name' => 'Bermuda','country_code' => '1441','country_status' => '0'),
            array('country_id' => '25','country_sortname' => 'BT','country_name' => 'Bhutan','country_code' => '975','country_status' => '0'),
            array('country_id' => '26','country_sortname' => 'BO','country_name' => 'Bolivia','country_code' => '591','country_status' => '0'),
            array('country_id' => '27','country_sortname' => 'BA','country_name' => 'Bosnia and Herzegovina','country_code' => '387','country_status' => '0'),
            array('country_id' => '28','country_sortname' => 'BW','country_name' => 'Botswana','country_code' => '267','country_status' => '0'),
            array('country_id' => '29','country_sortname' => 'BV','country_name' => 'Bouvet Island','country_code' => '55','country_status' => '0'),
            array('country_id' => '30','country_sortname' => 'BR','country_name' => 'Brazil','country_code' => '55','country_status' => '0'),
            array('country_id' => '31','country_sortname' => 'IO','country_name' => 'British Indian Ocean Territory','country_code' => '246','country_status' => '0'),
            array('country_id' => '32','country_sortname' => 'BN','country_name' => 'Brunei','country_code' => '673','country_status' => '0'),
            array('country_id' => '33','country_sortname' => 'BG','country_name' => 'Bulgaria','country_code' => '359','country_status' => '0'),
            array('country_id' => '34','country_sortname' => 'BF','country_name' => 'Burkina Faso','country_code' => '226','country_status' => '0'),
            array('country_id' => '35','country_sortname' => 'BI','country_name' => 'Burundi','country_code' => '257','country_status' => '0'),
            array('country_id' => '36','country_sortname' => 'KH','country_name' => 'Cambodia','country_code' => '855','country_status' => '0'),
            array('country_id' => '37','country_sortname' => 'CM','country_name' => 'Cameroon','country_code' => '237','country_status' => '0'),
            array('country_id' => '38','country_sortname' => 'CA','country_name' => 'Canada','country_code' => '1','country_status' => '0'),
            array('country_id' => '39','country_sortname' => 'CV','country_name' => 'Cape Verde','country_code' => '238','country_status' => '0'),
            array('country_id' => '40','country_sortname' => 'KY','country_name' => 'Cayman Islands','country_code' => '1345','country_status' => '0'),
            array('country_id' => '41','country_sortname' => 'CF','country_name' => 'Central African Republic','country_code' => '236','country_status' => '0'),
            array('country_id' => '42','country_sortname' => 'TD','country_name' => 'Chad','country_code' => '235','country_status' => '0'),
            array('country_id' => '43','country_sortname' => 'CL','country_name' => 'Chile','country_code' => '56','country_status' => '0'),
            array('country_id' => '44','country_sortname' => 'CN','country_name' => 'China','country_code' => '86','country_status' => '0'),
            array('country_id' => '45','country_sortname' => 'CX','country_name' => 'Christmas Island','country_code' => '61','country_status' => '0'),
            array('country_id' => '46','country_sortname' => 'CC','country_name' => 'Cocos (Keeling) Islands','country_code' => '672','country_status' => '0'),
            array('country_id' => '47','country_sortname' => 'CO','country_name' => 'Colombia','country_code' => '57','country_status' => '0'),
            array('country_id' => '48','country_sortname' => 'KM','country_name' => 'Comoros','country_code' => '269','country_status' => '0'),
            array('country_id' => '49','country_sortname' => 'CG','country_name' => 'Republic Of The Congo','country_code' => '242','country_status' => '0'),
            array('country_id' => '50','country_sortname' => 'CD','country_name' => 'Democratic Republic Of The Congo','country_code' => '242','country_status' => '0'),
            array('country_id' => '51','country_sortname' => 'CK','country_name' => 'Cook Islands','country_code' => '682','country_status' => '0'),
            array('country_id' => '52','country_sortname' => 'CR','country_name' => 'Costa Rica','country_code' => '506','country_status' => '0'),
            array('country_id' => '53','country_sortname' => 'CI','country_name' => 'Cote D\'Ivoire (Ivory Coast)','country_code' => '225','country_status' => '0'),
            array('country_id' => '54','country_sortname' => 'HR','country_name' => 'Croatia (Hrvatska)','country_code' => '385','country_status' => '0'),
            array('country_id' => '55','country_sortname' => 'CU','country_name' => 'Cuba','country_code' => '53','country_status' => '0'),
            array('country_id' => '56','country_sortname' => 'CY','country_name' => 'Cyprus','country_code' => '357','country_status' => '0'),
            array('country_id' => '57','country_sortname' => 'CZ','country_name' => 'Czech Republic','country_code' => '420','country_status' => '0'),
            array('country_id' => '58','country_sortname' => 'DK','country_name' => 'Denmark','country_code' => '45','country_status' => '0'),
            array('country_id' => '59','country_sortname' => 'DJ','country_name' => 'Djibouti','country_code' => '253','country_status' => '0'),
            array('country_id' => '60','country_sortname' => 'DM','country_name' => 'Dominica','country_code' => '1767','country_status' => '0'),
            array('country_id' => '61','country_sortname' => 'DO','country_name' => 'Dominican Republic','country_code' => '1809','country_status' => '0'),
            array('country_id' => '62','country_sortname' => 'TP','country_name' => 'East Timor','country_code' => '670','country_status' => '0'),
            array('country_id' => '63','country_sortname' => 'EC','country_name' => 'Ecuador','country_code' => '593','country_status' => '0'),
            array('country_id' => '64','country_sortname' => 'EG','country_name' => 'Egypt','country_code' => '20','country_status' => '0'),
            array('country_id' => '65','country_sortname' => 'SV','country_name' => 'El Salvador','country_code' => '503','country_status' => '0'),
            array('country_id' => '66','country_sortname' => 'GQ','country_name' => 'Equatorial Guinea','country_code' => '240','country_status' => '0'),
            array('country_id' => '67','country_sortname' => 'ER','country_name' => 'Eritrea','country_code' => '291','country_status' => '0'),
            array('country_id' => '68','country_sortname' => 'EE','country_name' => 'Estonia','country_code' => '372','country_status' => '0'),
            array('country_id' => '69','country_sortname' => 'ET','country_name' => 'Ethiopia','country_code' => '251','country_status' => '0'),
            array('country_id' => '70','country_sortname' => 'XA','country_name' => 'External Territories of Australia','country_code' => '61','country_status' => '0'),
            array('country_id' => '71','country_sortname' => 'FK','country_name' => 'Falkland Islands','country_code' => '500','country_status' => '0'),
            array('country_id' => '72','country_sortname' => 'FO','country_name' => 'Faroe Islands','country_code' => '298','country_status' => '0'),
            array('country_id' => '73','country_sortname' => 'FJ','country_name' => 'Fiji Islands','country_code' => '679','country_status' => '0'),
            array('country_id' => '74','country_sortname' => 'FI','country_name' => 'Finland','country_code' => '358','country_status' => '0'),
            array('country_id' => '75','country_sortname' => 'FR','country_name' => 'France','country_code' => '33','country_status' => '0'),
            array('country_id' => '76','country_sortname' => 'GF','country_name' => 'French Guiana','country_code' => '594','country_status' => '0'),
            array('country_id' => '77','country_sortname' => 'PF','country_name' => 'French Polynesia','country_code' => '689','country_status' => '0'),
            array('country_id' => '78','country_sortname' => 'TF','country_name' => 'French Southern Territories','country_code' => '262','country_status' => '0'),
            array('country_id' => '79','country_sortname' => 'GA','country_name' => 'Gabon','country_code' => '241','country_status' => '0'),
            array('country_id' => '80','country_sortname' => 'GM','country_name' => 'Gambia The','country_code' => '220','country_status' => '0'),
            array('country_id' => '81','country_sortname' => 'GE','country_name' => 'Georgia','country_code' => '995','country_status' => '1'),
            array('country_id' => '82','country_sortname' => 'DE','country_name' => 'Germany','country_code' => '49','country_status' => '0'),
            array('country_id' => '83','country_sortname' => 'GH','country_name' => 'Ghana','country_code' => '233','country_status' => '0'),
            array('country_id' => '84','country_sortname' => 'GI','country_name' => 'Gibraltar','country_code' => '350','country_status' => '0'),
            array('country_id' => '85','country_sortname' => 'GR','country_name' => 'Greece','country_code' => '30','country_status' => '0'),
            array('country_id' => '86','country_sortname' => 'GL','country_name' => 'Greenland','country_code' => '299','country_status' => '0'),
            array('country_id' => '87','country_sortname' => 'GD','country_name' => 'Grenada','country_code' => '1473','country_status' => '0'),
            array('country_id' => '88','country_sortname' => 'GP','country_name' => 'Guadeloupe','country_code' => '590','country_status' => '0'),
            array('country_id' => '89','country_sortname' => 'GU','country_name' => 'Guam','country_code' => '1671','country_status' => '0'),
            array('country_id' => '90','country_sortname' => 'GT','country_name' => 'Guatemala','country_code' => '502','country_status' => '0'),
            array('country_id' => '91','country_sortname' => 'XU','country_name' => 'Guernsey and Alderney','country_code' => '44','country_status' => '0'),
            array('country_id' => '92','country_sortname' => 'GN','country_name' => 'Guinea','country_code' => '224','country_status' => '0'),
            array('country_id' => '93','country_sortname' => 'GW','country_name' => 'Guinea-Bissau','country_code' => '245','country_status' => '0'),
            array('country_id' => '94','country_sortname' => 'GY','country_name' => 'Guyana','country_code' => '592','country_status' => '0'),
            array('country_id' => '95','country_sortname' => 'HT','country_name' => 'Haiti','country_code' => '509','country_status' => '0'),
            array('country_id' => '96','country_sortname' => 'HM','country_name' => 'Heard and McDonald Islands','country_code' => '0','country_status' => '0'),
            array('country_id' => '97','country_sortname' => 'HN','country_name' => 'Honduras','country_code' => '504','country_status' => '0'),
            array('country_id' => '98','country_sortname' => 'HK','country_name' => 'Hong Kong S.A.R.','country_code' => '852','country_status' => '0'),
            array('country_id' => '99','country_sortname' => 'HU','country_name' => 'Hungary','country_code' => '36','country_status' => '0'),
            array('country_id' => '100','country_sortname' => 'IS','country_name' => 'Iceland','country_code' => '354','country_status' => '0'),
            array('country_id' => '101','country_sortname' => 'IN','country_name' => 'India','country_code' => '91','country_status' => '0'),
            array('country_id' => '102','country_sortname' => 'ID','country_name' => 'Indonesia','country_code' => '62','country_status' => '0'),
            array('country_id' => '103','country_sortname' => 'IR','country_name' => 'Iran','country_code' => '98','country_status' => '0'),
            array('country_id' => '104','country_sortname' => 'IQ','country_name' => 'Iraq','country_code' => '964','country_status' => '0'),
            array('country_id' => '105','country_sortname' => 'IE','country_name' => 'Ireland','country_code' => '353','country_status' => '0'),
            array('country_id' => '106','country_sortname' => 'IL','country_name' => 'Israel','country_code' => '972','country_status' => '0'),
            array('country_id' => '107','country_sortname' => 'IT','country_name' => 'Italy','country_code' => '39','country_status' => '0'),
            array('country_id' => '108','country_sortname' => 'JM','country_name' => 'Jamaica','country_code' => '1876','country_status' => '0'),
            array('country_id' => '109','country_sortname' => 'JP','country_name' => 'Japan','country_code' => '81','country_status' => '0'),
            array('country_id' => '110','country_sortname' => 'XJ','country_name' => 'Jersey','country_code' => '44','country_status' => '0'),
            array('country_id' => '111','country_sortname' => 'JO','country_name' => 'Jordan','country_code' => '962','country_status' => '0'),
            array('country_id' => '112','country_sortname' => 'KZ','country_name' => 'Kazakhstan','country_code' => '7','country_status' => '0'),
            array('country_id' => '113','country_sortname' => 'KE','country_name' => 'Kenya','country_code' => '254','country_status' => '0'),
            array('country_id' => '114','country_sortname' => 'KI','country_name' => 'Kiribati','country_code' => '686','country_status' => '0'),
            array('country_id' => '115','country_sortname' => 'KP','country_name' => 'Korea North','country_code' => '850','country_status' => '0'),
            array('country_id' => '116','country_sortname' => 'KR','country_name' => 'Korea South','country_code' => '82','country_status' => '0'),
            array('country_id' => '117','country_sortname' => 'KW','country_name' => 'Kuwait','country_code' => '965','country_status' => '0'),
            array('country_id' => '118','country_sortname' => 'KG','country_name' => 'Kyrgyzstan','country_code' => '996','country_status' => '0'),
            array('country_id' => '119','country_sortname' => 'LA','country_name' => 'Laos','country_code' => '856','country_status' => '0'),
            array('country_id' => '120','country_sortname' => 'LV','country_name' => 'Latvia','country_code' => '371','country_status' => '0'),
            array('country_id' => '121','country_sortname' => 'LB','country_name' => 'Lebanon','country_code' => '961','country_status' => '0'),
            array('country_id' => '122','country_sortname' => 'LS','country_name' => 'Lesotho','country_code' => '266','country_status' => '0'),
            array('country_id' => '123','country_sortname' => 'LR','country_name' => 'Liberia','country_code' => '231','country_status' => '0'),
            array('country_id' => '124','country_sortname' => 'LY','country_name' => 'Libya','country_code' => '218','country_status' => '0'),
            array('country_id' => '125','country_sortname' => 'LI','country_name' => 'Liechtenstein','country_code' => '423','country_status' => '0'),
            array('country_id' => '126','country_sortname' => 'LT','country_name' => 'Lithuania','country_code' => '370','country_status' => '0'),
            array('country_id' => '127','country_sortname' => 'LU','country_name' => 'Luxembourg','country_code' => '352','country_status' => '0'),
            array('country_id' => '128','country_sortname' => 'MO','country_name' => 'Macau S.A.R.','country_code' => '853','country_status' => '0'),
            array('country_id' => '129','country_sortname' => 'MK','country_name' => 'Macedonia','country_code' => '389','country_status' => '0'),
            array('country_id' => '130','country_sortname' => 'MG','country_name' => 'Madagascar','country_code' => '261','country_status' => '0'),
            array('country_id' => '131','country_sortname' => 'MW','country_name' => 'Malawi','country_code' => '265','country_status' => '0'),
            array('country_id' => '132','country_sortname' => 'MY','country_name' => 'Malaysia','country_code' => '60','country_status' => '0'),
            array('country_id' => '133','country_sortname' => 'MV','country_name' => 'Maldives','country_code' => '960','country_status' => '0'),
            array('country_id' => '134','country_sortname' => 'ML','country_name' => 'Mali','country_code' => '223','country_status' => '0'),
            array('country_id' => '135','country_sortname' => 'MT','country_name' => 'Malta','country_code' => '356','country_status' => '0'),
            array('country_id' => '136','country_sortname' => 'XM','country_name' => 'Man (Isle of)','country_code' => '44','country_status' => '0'),
            array('country_id' => '137','country_sortname' => 'MH','country_name' => 'Marshall Islands','country_code' => '692','country_status' => '0'),
            array('country_id' => '138','country_sortname' => 'MQ','country_name' => 'Martinique','country_code' => '596','country_status' => '0'),
            array('country_id' => '139','country_sortname' => 'MR','country_name' => 'Mauritania','country_code' => '222','country_status' => '0'),
            array('country_id' => '140','country_sortname' => 'MU','country_name' => 'Mauritius','country_code' => '230','country_status' => '0'),
            array('country_id' => '141','country_sortname' => 'YT','country_name' => 'Mayotte','country_code' => '269','country_status' => '0'),
            array('country_id' => '142','country_sortname' => 'MX','country_name' => 'Mexico','country_code' => '52','country_status' => '0'),
            array('country_id' => '143','country_sortname' => 'FM','country_name' => 'Micronesia','country_code' => '691','country_status' => '0'),
            array('country_id' => '144','country_sortname' => 'MD','country_name' => 'Moldova','country_code' => '373','country_status' => '0'),
            array('country_id' => '145','country_sortname' => 'MC','country_name' => 'Monaco','country_code' => '377','country_status' => '0'),
            array('country_id' => '146','country_sortname' => 'MN','country_name' => 'Mongolia','country_code' => '976','country_status' => '0'),
            array('country_id' => '147','country_sortname' => 'MS','country_name' => 'Montserrat','country_code' => '1664','country_status' => '0'),
            array('country_id' => '148','country_sortname' => 'MA','country_name' => 'Morocco','country_code' => '212','country_status' => '0'),
            array('country_id' => '149','country_sortname' => 'MZ','country_name' => 'Mozambique','country_code' => '258','country_status' => '0'),
            array('country_id' => '150','country_sortname' => 'MM','country_name' => 'Myanmar','country_code' => '95','country_status' => '0'),
            array('country_id' => '151','country_sortname' => 'NA','country_name' => 'Namibia','country_code' => '264','country_status' => '0'),
            array('country_id' => '152','country_sortname' => 'NR','country_name' => 'Nauru','country_code' => '674','country_status' => '0'),
            array('country_id' => '153','country_sortname' => 'NP','country_name' => 'Nepal','country_code' => '977','country_status' => '0'),
            array('country_id' => '154','country_sortname' => 'AN','country_name' => 'Netherlands Antilles','country_code' => '599','country_status' => '0'),
            array('country_id' => '155','country_sortname' => 'NL','country_name' => 'Netherlands The','country_code' => '31','country_status' => '0'),
            array('country_id' => '156','country_sortname' => 'NC','country_name' => 'New Caledonia','country_code' => '687','country_status' => '0'),
            array('country_id' => '157','country_sortname' => 'NZ','country_name' => 'New Zealand','country_code' => '64','country_status' => '0'),
            array('country_id' => '158','country_sortname' => 'NI','country_name' => 'Nicaragua','country_code' => '505','country_status' => '0'),
            array('country_id' => '159','country_sortname' => 'NE','country_name' => 'Niger','country_code' => '227','country_status' => '0'),
            array('country_id' => '160','country_sortname' => 'NG','country_name' => 'Nigeria','country_code' => '234','country_status' => '0'),
            array('country_id' => '161','country_sortname' => 'NU','country_name' => 'Niue','country_code' => '683','country_status' => '0'),
            array('country_id' => '162','country_sortname' => 'NF','country_name' => 'Norfolk Island','country_code' => '672','country_status' => '0'),
            array('country_id' => '163','country_sortname' => 'MP','country_name' => 'Northern Mariana Islands','country_code' => '1670','country_status' => '0'),
            array('country_id' => '164','country_sortname' => 'NO','country_name' => 'Norway','country_code' => '47','country_status' => '0'),
            array('country_id' => '165','country_sortname' => 'OM','country_name' => 'Oman','country_code' => '968','country_status' => '0'),
            array('country_id' => '166','country_sortname' => 'PK','country_name' => 'Pakistan','country_code' => '92','country_status' => '0'),
            array('country_id' => '167','country_sortname' => 'PW','country_name' => 'Palau','country_code' => '680','country_status' => '0'),
            array('country_id' => '168','country_sortname' => 'PS','country_name' => 'Palestinian Territory Occupied','country_code' => '970','country_status' => '0'),
            array('country_id' => '169','country_sortname' => 'PA','country_name' => 'Panama','country_code' => '507','country_status' => '0'),
            array('country_id' => '170','country_sortname' => 'PG','country_name' => 'Papua new Guinea','country_code' => '675','country_status' => '0'),
            array('country_id' => '171','country_sortname' => 'PY','country_name' => 'Paraguay','country_code' => '595','country_status' => '0'),
            array('country_id' => '172','country_sortname' => 'PE','country_name' => 'Peru','country_code' => '51','country_status' => '0'),
            array('country_id' => '173','country_sortname' => 'PH','country_name' => 'Philippines','country_code' => '63','country_status' => '0'),
            array('country_id' => '174','country_sortname' => 'PN','country_name' => 'Pitcairn Island','country_code' => '64','country_status' => '0'),
            array('country_id' => '175','country_sortname' => 'PL','country_name' => 'Poland','country_code' => '48','country_status' => '0'),
            array('country_id' => '176','country_sortname' => 'PT','country_name' => 'Portugal','country_code' => '351','country_status' => '0'),
            array('country_id' => '177','country_sortname' => 'PR','country_name' => 'Puerto Rico','country_code' => '1787','country_status' => '0'),
            array('country_id' => '178','country_sortname' => 'QA','country_name' => 'Qatar','country_code' => '974','country_status' => '0'),
            array('country_id' => '179','country_sortname' => 'RE','country_name' => 'Reunion','country_code' => '262','country_status' => '0'),
            array('country_id' => '180','country_sortname' => 'RO','country_name' => 'Romania','country_code' => '40','country_status' => '0'),
            array('country_id' => '181','country_sortname' => 'RU','country_name' => 'Russia','country_code' => '70','country_status' => '0'),
            array('country_id' => '182','country_sortname' => 'RW','country_name' => 'Rwanda','country_code' => '250','country_status' => '0'),
            array('country_id' => '183','country_sortname' => 'SH','country_name' => 'Saint Helena','country_code' => '290','country_status' => '0'),
            array('country_id' => '184','country_sortname' => 'KN','country_name' => 'Saint Kitts And Nevis','country_code' => '1869','country_status' => '0'),
            array('country_id' => '185','country_sortname' => 'LC','country_name' => 'Saint Lucia','country_code' => '1758','country_status' => '0'),
            array('country_id' => '186','country_sortname' => 'PM','country_name' => 'Saint Pierre and Miquelon','country_code' => '508','country_status' => '0'),
            array('country_id' => '187','country_sortname' => 'VC','country_name' => 'Saint Vincent And The Grenadines','country_code' => '1784','country_status' => '0'),
            array('country_id' => '188','country_sortname' => 'WS','country_name' => 'Samoa','country_code' => '684','country_status' => '0'),
            array('country_id' => '189','country_sortname' => 'SM','country_name' => 'San Marino','country_code' => '378','country_status' => '0'),
            array('country_id' => '190','country_sortname' => 'ST','country_name' => 'Sao Tome and Principe','country_code' => '239','country_status' => '0'),
            array('country_id' => '191','country_sortname' => 'SA','country_name' => 'Saudi Arabia','country_code' => '966','country_status' => '0'),
            array('country_id' => '192','country_sortname' => 'SN','country_name' => 'Senegal','country_code' => '221','country_status' => '0'),
            array('country_id' => '193','country_sortname' => 'RS','country_name' => 'Serbia','country_code' => '381','country_status' => '0'),
            array('country_id' => '194','country_sortname' => 'SC','country_name' => 'Seychelles','country_code' => '248','country_status' => '0'),
            array('country_id' => '195','country_sortname' => 'SL','country_name' => 'Sierra Leone','country_code' => '232','country_status' => '0'),
            array('country_id' => '196','country_sortname' => 'SG','country_name' => 'Singapore','country_code' => '65','country_status' => '0'),
            array('country_id' => '197','country_sortname' => 'SK','country_name' => 'Slovakia','country_code' => '421','country_status' => '0'),
            array('country_id' => '198','country_sortname' => 'SI','country_name' => 'Slovenia','country_code' => '386','country_status' => '0'),
            array('country_id' => '199','country_sortname' => 'XG','country_name' => 'Smaller Territories of the UK','country_code' => '44','country_status' => '0'),
            array('country_id' => '200','country_sortname' => 'SB','country_name' => 'Solomon Islands','country_code' => '677','country_status' => '0'),
            array('country_id' => '201','country_sortname' => 'SO','country_name' => 'Somalia','country_code' => '252','country_status' => '0'),
            array('country_id' => '202','country_sortname' => 'ZA','country_name' => 'South Africa','country_code' => '27','country_status' => '0'),
            array('country_id' => '203','country_sortname' => 'GS','country_name' => 'South Georgia','country_code' => '995','country_status' => '0'),
            array('country_id' => '204','country_sortname' => 'SS','country_name' => 'South Sudan','country_code' => '211','country_status' => '0'),
            array('country_id' => '205','country_sortname' => 'ES','country_name' => 'Spain','country_code' => '34','country_status' => '0'),
            array('country_id' => '206','country_sortname' => 'LK','country_name' => 'Sri Lanka','country_code' => '94','country_status' => '0'),
            array('country_id' => '207','country_sortname' => 'SD','country_name' => 'Sudan','country_code' => '249','country_status' => '0'),
            array('country_id' => '208','country_sortname' => 'SR','country_name' => 'Suriname','country_code' => '597','country_status' => '0'),
            array('country_id' => '209','country_sortname' => 'SJ','country_name' => 'Svalbard And Jan Mayen Islands','country_code' => '47','country_status' => '0'),
            array('country_id' => '210','country_sortname' => 'SZ','country_name' => 'Swaziland','country_code' => '268','country_status' => '0'),
            array('country_id' => '211','country_sortname' => 'SE','country_name' => 'Sweden','country_code' => '46','country_status' => '0'),
            array('country_id' => '212','country_sortname' => 'CH','country_name' => 'Switzerland','country_code' => '41','country_status' => '0'),
            array('country_id' => '213','country_sortname' => 'SY','country_name' => 'Syria','country_code' => '963','country_status' => '0'),
            array('country_id' => '214','country_sortname' => 'TW','country_name' => 'Taiwan','country_code' => '886','country_status' => '0'),
            array('country_id' => '215','country_sortname' => 'TJ','country_name' => 'Tajikistan','country_code' => '992','country_status' => '0'),
            array('country_id' => '216','country_sortname' => 'TZ','country_name' => 'Tanzania','country_code' => '255','country_status' => '0'),
            array('country_id' => '217','country_sortname' => 'TH','country_name' => 'Thailand','country_code' => '66','country_status' => '0'),
            array('country_id' => '218','country_sortname' => 'TG','country_name' => 'Togo','country_code' => '228','country_status' => '0'),
            array('country_id' => '219','country_sortname' => 'TK','country_name' => 'Tokelau','country_code' => '690','country_status' => '0'),
            array('country_id' => '220','country_sortname' => 'TO','country_name' => 'Tonga','country_code' => '676','country_status' => '0'),
            array('country_id' => '221','country_sortname' => 'TT','country_name' => 'Trinidad And Tobago','country_code' => '1868','country_status' => '0'),
            array('country_id' => '222','country_sortname' => 'TN','country_name' => 'Tunisia','country_code' => '216','country_status' => '0'),
            array('country_id' => '223','country_sortname' => 'TR','country_name' => 'Turkey','country_code' => '90','country_status' => '0'),
            array('country_id' => '224','country_sortname' => 'TM','country_name' => 'Turkmenistan','country_code' => '7370','country_status' => '0'),
            array('country_id' => '225','country_sortname' => 'TC','country_name' => 'Turks And Caicos Islands','country_code' => '1649','country_status' => '0'),
            array('country_id' => '226','country_sortname' => 'TV','country_name' => 'Tuvalu','country_code' => '688','country_status' => '0'),
            array('country_id' => '227','country_sortname' => 'UG','country_name' => 'Uganda','country_code' => '256','country_status' => '0'),
            array('country_id' => '228','country_sortname' => 'UA','country_name' => 'Ukraine','country_code' => '380','country_status' => '0'),
            array('country_id' => '229','country_sortname' => 'AE','country_name' => 'United Arab Emirates','country_code' => '971','country_status' => '0'),
            array('country_id' => '230','country_sortname' => 'GB','country_name' => 'United Kingdom','country_code' => '44','country_status' => '0'),
            array('country_id' => '231','country_sortname' => 'US','country_name' => 'United States','country_code' => '1','country_status' => '0'),
            array('country_id' => '232','country_sortname' => 'UM','country_name' => 'United States Minor Outlying Islands','country_code' => '1','country_status' => '0'),
            array('country_id' => '233','country_sortname' => 'UY','country_name' => 'Uruguay','country_code' => '598','country_status' => '0'),
            array('country_id' => '234','country_sortname' => 'UZ','country_name' => 'Uzbekistan','country_code' => '998','country_status' => '0'),
            array('country_id' => '235','country_sortname' => 'VU','country_name' => 'Vanuatu','country_code' => '678','country_status' => '0'),
            array('country_id' => '236','country_sortname' => 'VA','country_name' => 'Vatican City State (Holy See)','country_code' => '39','country_status' => '0'),
            array('country_id' => '237','country_sortname' => 'VE','country_name' => 'Venezuela','country_code' => '58','country_status' => '0'),
            array('country_id' => '238','country_sortname' => 'VN','country_name' => 'Vietnam','country_code' => '84','country_status' => '0'),
            array('country_id' => '239','country_sortname' => 'VG','country_name' => 'Virgin Islands (British)','country_code' => '1284','country_status' => '0'),
            array('country_id' => '240','country_sortname' => 'VI','country_name' => 'Virgin Islands (US)','country_code' => '1340','country_status' => '0'),
            array('country_id' => '241','country_sortname' => 'WF','country_name' => 'Wallis And Futuna Islands','country_code' => '681','country_status' => '0'),
            array('country_id' => '242','country_sortname' => 'EH','country_name' => 'Western Sahara','country_code' => '212','country_status' => '0'),
            array('country_id' => '243','country_sortname' => 'YE','country_name' => 'Yemen','country_code' => '967','country_status' => '0'),
            array('country_id' => '244','country_sortname' => 'YU','country_name' => 'Yugoslavia','country_code' => '38','country_status' => '0'),
            array('country_id' => '245','country_sortname' => 'ZM','country_name' => 'Zambia','country_code' => '260','country_status' => '0'),
            array('country_id' => '246','country_sortname' => 'ZW','country_name' => 'Zimbabwe','country_code' => '263','country_status' => '0')
          );

         foreach($countries as $key => $country){
            Countries::updateOrCreate(
                [
                    'country_name' => $country['country_name']
                ],[
                    'id' => $country['country_id'],
                    'country_abbr' => $country['country_sortname'],
                    'country_code' => $country['country_code'],
                    'status' => $country['country_status'],
                ]
            );
         }
    }
}
